# Generated by Django 3.2 on 2022-06-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
