# Generated by Django 3.2 on 2022-03-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0002_auto_20220325_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='date_joined',
            new_name='date_created',
        ),
    ]
