# Generated by Django 3.2 on 2022-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0003_rename_date_joined_artisan_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
