# Generated by Django 3.2 on 2022-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0004_alter_artisan_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='profession_name',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='artisan',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
