# Generated by Django 3.2 on 2022-03-25 16:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0005_auto_20220325_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='date_created',
        ),
        migrations.AddField(
            model_name='artisan',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='profession_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisan.profession'),
        ),
        migrations.AddField(
            model_name='artisan',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
