# Generated by Django 3.2 on 2022-04-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0010_rename_date_joined_artisan_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='profession_name',
        ),
    ]
