# Generated by Django 3.2 on 2022-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0011_remove_artisan_profession_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AddField(
            model_name='artisan',
            name='profession_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
