# Generated by Django 3.2 on 2022-04-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artisan', '0012_auto_20220408_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.CharField(max_length=20, null=True, unique=True)),
                ('client', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('pay', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
