# Generated by Django 3.2 on 2022-04-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0015_auto_20220423_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='profession_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='completedjob',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='completedjob',
            name='job_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='viewedjob',
            name='category',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='viewedjob',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='viewedjob',
            name='job_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
