# Generated by Django 3.2 on 2022-04-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0016_auto_20220423_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedjob',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedJob',
        ),
        migrations.DeleteModel(
            name='ViewedJob',
        ),
    ]
