# Generated by Django 3.2 on 2022-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0019_auto_20220423_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedjob',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
