# Generated by Django 3.2 on 2022-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0020_viewedjob_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedjob',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
