# Generated by Django 3.2 on 2022-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0021_completedjob_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedjob',
            old_name='date',
            new_name='date_accepted',
        ),
        migrations.AddField(
            model_name='viewedjob',
            name='date_vewd',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
