# Generated by Django 3.2 on 2022-04-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0023_auto_20220426_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedjob',
            name='accepted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
     #   migrations.AlterField(
      #      model_name='viewedjob',
       #     name='date_accepted',
        #    field=models.DateField(auto_now_add=True, null=True),
        #),
    ]
