# Generated by Django 3.2 on 2022-04-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0024_auto_20220426_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedjob',
            name='date_accepted',
        ),
    ]
