# Generated by Django 3.2 on 2022-04-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0025_remove_viewedjob_date_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedjob',
            name='date_accepted',
        ),
    ]
