# Generated by Django 3.2 on 2022-04-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0026_remove_completedjob_date_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedjob',
            name='accepted',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
