# Generated by Django 3.2 on 2022-04-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0027_alter_viewedjob_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedjob',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='viewedjob',
            name='accepted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
