## Generated by Django 3.2 on 2022-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0028_auto_20220427_0044'),
    ]

    operations = [
       # migrations.AddField(
        #    model_name='viewedjob',
        #    name='completed',
        #    field=models.CharField(blank=True, default='No', max_length=100, null=True),
       # ),
    ]
