# Generated by Django 3.2 on 2022-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0029_viewedjob_completed'),
    ]

    operations = [
        #migrations.AlterField(
         #   model_name='viewedjob',
         #   name='completed',
         #   field=models.BooleanField(default=False),
       # ),
    ]
