# Generated by Django 3.2 on 2022-04-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0032_viewedjob_completed'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='viewedjob',
          #  name='completed',
       # ),
    ]
