# Generated by Django 3.2 on 2022-04-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0034_viewedjob_completed_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedjob',
            name='completed_job',
        ),
    ]
