# Generated by Django 3.2 on 2022-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0035_remove_viewedjob_completed_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedjob',
            name='work_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
