# Generated by Django 3.2 on 2022-05-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0038_alter_viewedjob_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewedjob',
            old_name='order_id',
            new_name='job_order_id',
        ),
    ]
