# Generated by Django 4.0.2 on 2022-07-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_servicerequest_location'),
        ('artisan', '0041_alter_artisan_profession_name'),
    ]

    operations = [
        #migrations.AlterField(
         #   model_name='artisan',
          #  name='profession_name',
           # field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        #),
    ]
