# Generated by Django 4.0.2 on 2022-07-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0043_artisan_job_name_alter_artisan_profession_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='profession_name',
        ),
    ]
