# Generated by Django 4.0.2 on 2022-07-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0044_remove_artisan_profession_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='job_name',
            new_name='profession_name',
        ),
    ]
