# Generated by Django 4.0.2 on 2022-07-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artisan', '0045_rename_job_name_artisan_profession_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, null=True, unique=True)),
                ('account_type', models.CharField(max_length=200, null=True, unique=True)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('payment_date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BankDetails',
            },
        ),
    ]
