# Generated by Django 4.0.2 on 2022-07-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0046_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='account_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
