# Generated by Django 4.0.2 on 2022-07-10 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artisan', '0047_bankdetails_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_name',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_type',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisan_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
