# Generated by Django 4.0.2 on 2022-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0048_alter_bankdetails_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
