# Generated by Django 3.2 on 2022-01-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='payment_id',
        ),
    ]
