# Generated by Django 3.2 on 2022-04-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0013_completedjob'),
        ('products', '0003_auto_20220225_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='artisan_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisan.artisan'),
        ),
    ]
