# Generated by Django 3.2 on 2022-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220420_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
