# Generated by Django 3.2 on 2022-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0013_completedjob'),
        ('products', '0009_orderitem_artisan_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='artisan_assigned',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='artisan_assigned',
            field=models.ManyToManyField(blank=True, to='artisan.Artisan'),
        ),
    ]
