# Generated by Django 3.2 on 2022-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0022_auto_20220425_1403'),
        ('products', '0011_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='artisan_assigned',
            field=models.ManyToManyField(blank=True, related_name='assignee', to='artisan.Artisan'),
        ),
    ]
