# Generated by Django 3.2 on 2022-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0022_auto_20220425_1403'),
        ('products', '0012_alter_orderitem_artisan_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='artisan_assigned',
            field=models.ManyToManyField(blank=True, to='artisan.Artisan'),
        ),
    ]
