# Generated by Django 3.2 on 2022-04-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_orderitem_artisan_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_accepted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
