# Generated by Django 3.2 on 2022-04-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_orderitem_accepted'),
    ]

    operations = [
       # migrations.RemoveField(
        #    model_name='orderitem',
         #   name='date_accepted',
        #),
    ]
