# Generated by Django 3.2 on 2022-04-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_orderitem_date'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='orderitem',
          #  name='date',
        #),
    ]
