# Generated by Django 3.2 on 2022-04-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_orderitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accepted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
