# Generated by Django 3.2 on 2022-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_orderitem_accepted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='completed',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
