# Generated by Django 3.2 on 2022-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20220429_2051'),
    ]

    operations = [
       # migrations.AlterField(
        #    model_name='orderitem',
         #   name='completed',
          #  field=models.BooleanField(default=False),
        #),
    ]
