# Generated by Django 3.2 on 2022-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_orderitem_completed'),
    ]

    operations = [
        #migrations.AddField(
           # model_name='orderitem',
           # name='completed',
           # field=models.BooleanField(default=False),
       # ),
    ]
