# Generated by Django 3.2 on 2022-04-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_orderitem_completed_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='completed_job',
        ),
    ]
