# Generated by Django 3.2 on 2022-06-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_ourlocations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurLocations',
        ),
    ]
