# Generated by Django 3.2 on 2022-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_delete_ourlocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'OurLocation',
            },
        ),
    ]
