# Generated by Django 4.0.2 on 2022-06-23 13:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artisan', '0039_rename_order_id_viewedjob_job_order_id'),
        ('products', '0031_ourlocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('accepted', models.CharField(blank=True, default='No', max_length=100, null=True)),
                ('accepted_date', models.DateField(auto_now_add=True, null=True)),
                ('work_done', models.BooleanField(default=False, null=True)),
                ('artisan', models.ManyToManyField(blank=True, to='artisan.Artisan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ServiceRequest',
                'ordering': ['-date_created'],
            },
        ),
    ]
