# Generated by Django 4.0.2 on 2022-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_serviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc1', models.CharField(blank=True, max_length=100, null=True)),
                ('desc2', models.CharField(blank=True, max_length=100, null=True)),
                ('desc3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
