# Generated by Django 4.0.2 on 2022-06-28 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0039_rename_order_id_viewedjob_job_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0038_remove_jobpost_img_jobpost_number_of_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=200)),
                ('number_of_people', models.IntegerField(default=1)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('accepted', models.CharField(blank=True, default='No', max_length=100, null=True)),
                ('accepted_date', models.DateField(auto_now_add=True, null=True)),
                ('work_done', models.BooleanField(default=False, null=True)),
                ('artisan_assigned', models.ManyToManyField(blank=True, to='artisan.Artisan')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisan.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PostJob',
                'ordering': ['-date_created'],
            },
        ),
    ]
