# Generated by Django 4.0.2 on 2022-06-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_postjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
