# Generated by Django 4.0.2 on 2022-06-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_delete_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='price',
        ),
        migrations.AddField(
            model_name='postjob',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
