# Generated by Django 4.0.2 on 2022-06-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_postjob_paid_remove_postjob_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='job_title',
        ),
        migrations.AddField(
            model_name='postjob',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
