# Generated by Django 4.0.2 on 2023-05-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_servicerequest_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'verbose_name_plural': 'Payment Detail'},
        ),
    ]
